[theme]
primaryColor = "#ff3b30"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#e0e0e0"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal" # Cacher le hamburger menu autant que possible
showErrorDetails = false
